### PR TITLE
GH Action tweak

### PR DESCRIPTION
**Pull request by bumblefudge**
just testing to see if I can fix the self-render GH action by adding a repo secret in repo settings

### CODE REVIEW

**Comment by bumblefudge** [comment]
image
just a regular ol' SSH key

**Comment by JaceHensley** [comment]
It's odd because it seems like it should already be working I don't see any errors in the action https://github.com/decentralized-identity/credential-manifest/runs/3036541242?check_suite_focus=true

**Comment by JaceHensley** [comment]
I think I figured out why the original wallet-and-credential-interactions generated html was able to not be checked in. The `publish_dir` is a nested folder in the project https://github.com/decentralized-identity/wallet-and-credential-interactions/blob/main/.github/workflows/build-spec.yml#L27, meaning the .gitignore file isn’t contained in the published folder. So the `index.html` gets checked in to the docs branch because there is no `.gitignore` in that branch :sweat_smile: so we could do something like that, or we could just delete the `.gitignore` within the GH action

**Comment by JaceHensley** [comment]
close in favor of #64

**Pull request closed without merging**
