### PR TITLE
Add Credential Application reference in Credential Fulfillment

### LINKED ISSUE #96: Credential Fulfillment should reference a Credential Application
1. An issuer publishes a Credential Manifest
2. A want-to-be holder submits a Credential Application against the Manifest
3. The issuer fulfills the application, submitting a Credential Fulfillment to the soon-to-be holder

If this flow is a correct understanding of the specification, I note a gap between (2) and (3) where the Credential Fulfillment object does not have the ability to reference a Credential Application. I expect that each object is uniquely identified, and further:
- Credential Applications reference a Credential Manifest by ID
- Credential Fulfillments reference both Credential Applications and Credential Manifests by ID

The ID linkage is missing!

### PR DESCRIPTION
**Pull request by decentralgabe**
Fixes #96

### CODE REVIEW

**Comment by csuwildcat** [comment]
@decentralgabe not sure this should be a MUST unless there was an Application - what if you want to deliver a credential without requiring application?

**Comment by decentralgabe** [comment]
> @decentralgabe not sure this should be a MUST unless there was an Application - what if you want to deliver a credential without requiring application?

Then why use a credential fulfillment object at all? Why not just send the credential over?

**Comment by csuwildcat** [comment]
> > @decentralgabe not sure this should be a MUST unless there was an Application - what if you want to deliver a credential without requiring application?
> 
> Then why use a credential fulfillment object at all? Why not just send the credential over?

Because maybe you want the wrapper that references the Credential Manifest so the wallet has the style/rendering info related to it 😉

**Comment by decentralgabe** [comment]
If that is the intention of manifest, then some other language in the spec should be adjusted to reflect that intent.

Example:
> The Credential Manifest is a common data format for describing the inputs a Subject must provide to an Issuer for subsequent evaluation and issuance of the credential(s) indicated in the Credential Manifest.

A mention of utility independent of issuance, or event post-issuance could be added here.

> Credential Manifests are a resource format that defines preconditional requirements, **Issuer style preferences**, and other facets User Agents utilize to **help articulate and select the inputs necessary for processing and issuance** of a specified credential.

I think this makes sense, though I view display a little different from 'processing'.

Mostly nit picking 😄

**Review by csuwildcat — APPROVED** [review]

**Pull request merged**
